// apps/web/src/lib/covers/BadstuCovers.svelte
<script lang="ts">
  import kroloftet from '$lib/assets/kroloftet.jpeg'
  import langkaia from '$lib/assets/langkaia.jpeg'
  import sukkerbiten from '$lib/assets/sukkerbiten.jpg'
  import sagene from '$lib/assets/sagene.jpg'

  import { type AllLocationNames } from '@badstu/data/meta'

  const props: { location: AllLocationNames; class: string } = $props()
  const [imageSrc, offset] = $derived.by(() => {
    switch (props.location) {
      case 'Sagene Folkebad':
        return [sagene, -100] as const
      case 'Langkaia':
        return [langkaia, -177] as const
      case 'Sukkerbiten':
        return [sukkerbiten, -177] as const
      case 'Kroloftet':
        return [kroloftet, -177] as const
    }
  })
</script>

<img class={['image', props.class]} src={imageSrc} alt="Image" style="--offset: {offset}px" />

<style>
  .image {
    object-fit: cover;
    object-position: 0 var(--offset);
  }
</style>

// apps/web/src/components/BadstuDay/BadstuCovers.tsx
import type { AllLocationNames } from '@badstu/data/meta'
import Image from 'next/image'
import kroloftet from '@/assets/kroloftet.jpeg'
import langkaia from '@/assets/langkaia.jpeg'
import sukkerbiten from '@/assets/sukkerbiten.jpg'
import sagene from '@/assets/sagene.jpg'

interface BadstuCoversProps {
  location: AllLocationNames
  className?: string
}

export default function BadstuCovers({ location, className }: BadstuCoversProps) {
  const getImageData = () => {
    switch (location) {
      case 'Sagene Folkebad':
        return { src: sagene, offset: 61 }
      case 'Langkaia':
        return { src: langkaia, offset: 50 }
      case 'Sukkerbiten':
        return { src: sukkerbiten, offset: 45 }
      case 'Kroloftet':
        return { src: kroloftet, offset: 48 }
      default:
        return { src: sagene, offset: 50 }
    }
  }

  const { src, offset } = getImageData()

  return (
    <Image
      src={src}
      alt=""
      fill
      className={className}
      style={{
        objectFit: 'cover',
        objectPosition: `0 ${offset}%`,
      }}
      priority
    />
  )
}
