// apps/web/src/lib/badstu-day/DiffSinceTimer.svelte
<script lang="ts">
  import { differenceInMinutes } from 'date-fns'
  import { onMount } from 'svelte'

  const { lastUpdated }: { lastUpdated: Date } = $props()

  let counter = $state(0)

  onMount(() => {
    const interval = setInterval(() => {
      counter++
    }, 30_000)

    return () => {
      clearInterval(interval)
    }
  })
</script>

{#key counter}
  <span>{differenceInMinutes(new Date(), lastUpdated, { roundingMethod: 'round' })}</span>
{/key}

// apps/web/src/components/BadstuDay/DiffSinceTimer.tsx
'use client'

import { differenceInMinutes } from 'date-fns'
import { useEffect, useState } from 'react'

interface DiffSinceTimerProps {
  lastUpdated: Date
}

export default function DiffSinceTimer({ lastUpdated }: DiffSinceTimerProps) {
  const [counter, setCounter] = useState(0)

  useEffect(() => {
    const interval = setInterval(() => {
      setCounter((c) => c + 1)
    }, 30_000)

    return () => {
      clearInterval(interval)
    }
  }, [])

  return <span key={counter}>{differenceInMinutes(new Date(), lastUpdated, { roundingMethod: 'round' })}</span>
}
